### ISSUE TITLE
问一下搭建的问题

### ISSUE THREAD

**Issue by AndyNull** [AlphabugX/Alphalog#17]
那个域名需要解析一些什么到公网ip啊？

**Comment by AlphabugX** [comment]
A.Domain.com => A record    =>  IP

B.Domain.com => NS record  =>  A.Domain name

**Comment by AndyNull** [comment]
> A.Domain.com => A record => IP
> 
> B.Domain.com => NS record => A.Domain name

哦哦，谢谢，那和其他的差不多，哈哈

**Comment by AndyNull** [comment]
对了，这个搭建起来是没有前端面板的吧

**Comment by AlphabugX** [comment]
"Front-end" folder, modify the interface in the file, and hang the back-end code

**Comment by AndyNull** [comment]
> "Front-end" folder, modify the interface in the file, and hang the back-end code

好的，谢谢
